language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install coveralls
  - pip install pytest pytest-cov
  - pip install -r requirements.txt
script:
  - py.test --cov . --cov-report term-missing
after_script:
  - coveralls
